variable "region" {}
variable "ami_filter" {}
variable "internet_cidr" {}
variable "vpc_range" {}
variable "private_network_range" {}
variable "private_network_range_2" {}
variable "public_network_range" {}
variable "public_network_range_2" {}
variable "instance_type" {}
variable "db_username" {}
variable "db_password" {}